### PR TITLE
Fix for Dialer.LookupPartition

### PR DESCRIPTION
**Pull request by scarbo87**
There is no break in forever loop, so we will never receive error “ UnknownTopicOrPartition” on line 181. My code fixes case when there is no partitions found.

### CODE REVIEW

**Comment by scarbo87** [comment]
Of course

**Comment by scarbo87** [comment]
I was wrong, if you use `context.WithTimeout`, then will exit this function `LookupPartition` by timeout.

But, if you set up a Kafka with an option `auto.create.topics.enable=false`, then the error `t.TopicErrorCode=3 (UNKNOWN_TOPIC_OR_PARTITION)` on this [line](https://github.com/segmentio/kafka-go/blob/master/conn.go#L758) will not be processed.
On this [line](https://github.com/segmentio/kafka-go/blob/master/dialer.go#L160) partitions and err will equlas nil, this is wrong.

**Comment by achille-roussel** [comment]
@scarbo87 should we always return `UnknownTopicOrPartition` if `len(partitions) == 0` ?

**Comment by scarbo87** [comment]
No, this is not a good solution.

Currently I found two problems in the code.

1. We need to process sleep boolean result on line XXX, otherwise we ignore context and have memory leak.
2. If we connect to kafka and topic not exists, then on line XXX currently we will not return error, because c.topic will be always empty string.

I will take care of this. Let me know if you agree.

**Comment by scarbo87** [comment]
@achille-roussel, this fix is more correct

**Pull request merged**
