### PR TITLE
Downgrade various api versions to be compatible with kafka 0.10.1

### PR DESCRIPTION
**Pull request by tsholmes**
The versions of many api calls made aren't compatible with kafka 0.10.1. These changes downgrade them for compatibility. This likely isn't the full set of changes needed for support, but can be a good starting point.

### CODE REVIEW

**Comment by achille-roussel** [comment]
Looks like you have a typo in one of the tests
```
./syncgroup_test.go:58: TestsyncGroupResponseV0 has malformed name: first letter after 'Test' must not be lowercase
```

**Comment by tsholmes** [comment]
That blind find-replace coming back to bite me

**Comment by achille-roussel** [comment]
Do you mind vendoring your dependency on this branch before we merge to master? That way we can test things a little in production before moving forward.

Or maybe we'll wait until https://github.com/segmentio/kafka-go/pull/80 is ready and integrate those changes so we can actually do proper API version discovery.

**Comment by tsholmes** [comment]
Oh yeah I didn't intend this to merge as-is, more as a starting point for discussion. I'm vendoring this branch

**Comment by Pryz** [comment]
Seems like our tests are not catching those issues. See https://github.com/segmentio/kafka-go/pull/80

**Comment by yacn** [comment]
Any update on this? I was just bit by this, the cluster we have is 0.10.1 and I'm not able to get any data back from it using the latest version of the library.

**Pull request merged**
