### PR TITLE
feat(sasl): add GSSAPI as authentication mechanism

### PR DESCRIPTION
**Pull request by mrolla**
This PR adds GSSAPI via Kerberos authentication mechanism.

Addresses https://github.com/segmentio/kafka-go/issues/237 and partly https://github.com/segmentio/kafka-go/issues/539.

Currently, it's missing docker compose support for testing e2e, but I'll add that asap.

### CODE REVIEW

**Comment by chy373** [comment]
I need this feature very much! can this pull request be reviewed?

**Comment by mentalisttraceur** [comment]
**Caution**! As far as I know, no implementation of GSSAPI for this library can work in the general case unless it has a change in `dialer.go` to pass the broker's hostname/FQDN from the dialer code into the SASL mechanism!

It will only work in the special case where you only need to dial one broker with that mechanism. (Or I guess when every broker somehow has the same SPN, but I'm not sure if this is common or deprecated/discouraged?)

(More comments when I have time.)

**Comment by mentalisttraceur** [comment]
I say my last comment from having added a GSSAPI mechanism for this library back in mid-November for my employer, where we have a cluster with many Kafka brokers, and we have the use case of reading/dialing multiple brokers with one `kafka.Reader`/`kafka.Dialer`.

We intend to do a pull request soon (but for legal reasons I'm not speaking for my employer, and I'm not promising/guaranteeing anything). But y'all know how it goes when it's part of a job:

1. I'm on a small team with many competing priorities, and

2. it's still going through some prolonged testing in our environment to see if there are any subtle issues that crop up after prolonged execution, with large volumes of data, etc.

If this was my own personal contribution I would just paste in here all of the relevant diffs/code I wrote, but I'm not authorized to just casually make that decision on my own. So for now I'll just say:

1. In the SPN (`kafka/domain` in this pull request's example), only the `kafka` part seems reasonably possible to configure for an entire Kafka cluster - the `domain` part needs to be different each broker.

2. Currently, in this library, one `sasl.Mechanism`/`kafka.Dialer` can be used for connecting to multiple brokers.

3. It is a non-obvious regression and pitfall for human error if the GSSAPI SASL mechanism in particular can only work with one broker at a time. It would force users of this library to connect to each broker individually when for example a single `kafka.Reader` might have been sufficient. It would take some knowledge of the internals/details of Kerberos/GSSAPI for a user of this library to even know that this is a potential problem.

4. The `sasl.Mechanism` code can't know which broker `Start` is being called for unless code in `dialer.go` passes that information through before/during calling `Start`.

**Comment by mrolla** [comment]
That's some great feedback @mentalisttraceur, thanks!

I did develop and test this in a very controlled environment (you guessed, one broker) and wanted to have this out in the open to collect some feedbacks and use cases as my exposure to Kerberos and GSSAPI in general is kinda limited.

I will be back working on this very soon with the changes to the dialer to propagate the domain and in general testing with multiple brokers scenarios.

If in the meantime you manage to open a PR that supersedes this one, please feel free to ping me and I'll gladly close mine.

**Comment by achille-roussel** [comment]
Should we close in favor of https://github.com/segmentio/kafka-go/pull/598 ?

**Comment by mrolla** [comment]
@achille-roussel I'm going ahead and close this PR. Reading what you suggested in #598, I'm going ahead and open a new PR which basically just injects the address (needed for GSSAPI) into the authentication functions via the context (idiomatic in a way).

**Pull request closed without merging**
