### PR TITLE
add docs on how to list topics

### PR DESCRIPTION
**Pull request by aultimus**
This pull request adds documentation on how to get a list of all topics in kafka.

This documentation addresses how to list topics in the current version of kafka-go without adding new functionality.
This removes the need for this PR: https://github.com/segmentio/kafka-go/pull/520

### CODE REVIEW

**Comment by aultimus** [comment]
If this is popular functionality would it make more sense to add a function to return a unique list of topics rather than the documentation?

**Comment by achille-roussel** [comment]
Potentially, let's see how things evolve after improving our documentation? We could also open an issue to collect feedback, and maybe other ideas about which APIs we'd like to add?

**Review by achille-roussel — APPROVED** [review]

**Comment by yartashes** [comment]
@aultimus if kafka api makes it possible to directly get a list of topics why not use it. I don't understand what is the point of getting the list in an implicit way

**Comment by aultimus** [comment]
@nlsun @yartashes Once the public topic scanner interface lands lets update the docs to show how to use it, but these docs will suffice in the meantime

**Pull request merged**
