### PR TITLE
add error logger

### PR DESCRIPTION
**Pull request by achille-roussel**
This PR adds the ability to configure a logger specifically to report errors on kafka readers. This is useful to avoid the flood of common logs under normal situation and only surface the exceptional events that occur within the readers.

### CODE REVIEW

**Comment by f2prateek** [comment]
> This is useful to avoid the flood of common logs under normal situation 

Shouldn't those normal logs be "debug"? Can you highlight an example of a log for which you'd want to use an error logger, and one for which you wouldn't?

**Comment by f2prateek** [comment]
Ah, this isn't using `events.Logger` so we don't have levels here.

**Comment by achille-roussel** [comment]
Yeah, for better compatibility this package uses the standard library only.

**Comment by achille-roussel** [comment]
Thanks for the review!

**Pull request merged**
