### PR TITLE
fix bug that when time is zero, writeTime doesn't set to the msgs

### PR DESCRIPTION
**Pull request by CodeRushing**
This bug cause the producer message will be deleted very soon

### CODE REVIEW

**Comment by abraithwaite** [comment]
Can you provide a little more context?  What's the problem you're observing, and how does this fix it?

As far as I can tell, this won't change the behavior at all (unless I'm missing something).

**Comment by abraithwaite** [comment]
> I think the problem is msg is a local variable, it's not actually modifying the slice (unless I'm missing something).

idiot facepalm gif-source

Makes a copy, and it's not a pointer.  Duh.

**Comment by CodeRushing** [comment]
@achille-roussel  Done

**Comment by achille-roussel** [comment]
Thanks for your contribution!

**Pull request merged**
