### PR TITLE
ReferenceHash balancer

### PR DESCRIPTION
**Pull request by fracasula**
Hey guys, can I have some feedback on this PR please?

I've opened it due to [this issue](https://github.com/segmentio/kafka-go/issues/905).

### CODE REVIEW

**Comment by rhansen2** [comment]
HI @fracasula,

Thanks for the contribution. 
 
Overall this looks good to me.

Could you also update the compatibility section of the README to mention this balancer?

Thanks!

**Comment by fracasula** [comment]
> Could you also update the compatibility section of the README to mention this balancer?

There you go @rhansen2 ([commit](https://github.com/segmentio/kafka-go/pull/906/commits/1476d972d9502a2c41c230d66983ff4be86a11ba)) :slightly_smiling_face:

**Comment by rhansen2** [comment]
Thanks @fracasula!

Unfortunately I can't merge until the checks all pass. I think you just need to rebase to the tip of main so you have [this](https://github.com/segmentio/kafka-go/commit/aedfa487fa1c9aaf8c9076f127d8e2cc079b64a7) commit in your branch.

**Comment by fracasula** [comment]
> Unfortunately I can't merge until the checks all pass. I think you just need to rebase to the tip of main so you have [this](https://github.com/segmentio/kafka-go/commit/aedfa487fa1c9aaf8c9076f127d8e2cc079b64a7) commit in your branch.

@rhansen2 I rebased and that commit is included now. However one test is still failing but it's not related to this PR.

This is the failing test:
> --- FAIL: TestReaderReadCompactedMessage (125.08s)

Full log [here](https://circleci.com/api/v1.1/project/github/segmentio/kafka-go/9970/output/105/0?file=true&allocation-id=6285fb057b5d245a3d4548dc-0-build%2F6DA715DF).

I can't re-run the build either so what do you suggest we do?

**Comment by fracasula** [comment]
Did you re-run [this one](https://app.circleci.com/pipelines/github/segmentio/kafka-go/920/workflows/91e71198-5411-4f17-b4f7-9080ba107d01/jobs/9972)? It looks like the build is finally green :+1:

**Comment by rhansen2** [comment]
Yup it looked like just a transient timeout.

**Pull request merged**
