### PR TITLE
Only refresh metadata on success (#672)

### PR DESCRIPTION
**Pull request by omaskery**
Whilst I've made the changes that were agreed in the [GitHub issue](https://github.com/segmentio/kafka-go/issues/672), I haven't done any testing. Please advise on any testing you'd like me to do, above and beyond the unit tests that I assume will be run automatically on the PR after I've submitted it.

Note: I will endeavor to test that this change _actually fixes_ the issue on Monday when I'm back at work (and have access to the codebase where the issue presents).

### CODE REVIEW

**Comment by achille-roussel** [comment]
Thanks for opening the pull request @omaskery!

Unless it turns out to be too much efforts (these code paths are well exercised), having a test would be a great addition. We'd want to be able to trigger an error, which could be achieved with a construct like this maybe?

```go
transport := &kafka.Transport{
    Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
        return nil, errSomethingIsBroken
    },
}
```

Using this transport in the test will cause all requests to fail, then the test would perform a `kafka.(*Client).CreateTopics` and verify that the method call returns an error.

**Comment by omaskery** [comment]
Hi, sorry for the delay, I am still alive and will try and add the tests you mention - and to test it in my work. I'm afraid I've been particularly busy recently and haven't gotten back to this work.

**Comment by omaskery** [comment]
Hi, I've finally had a chance to test this fix, and it looks like my initial solution wasn't good enough.

It turns out that when Kafka returns an error that the topic has an invalid configuration, the lower level communication code returns a `createtopics.Response` object which internally contains the error information. The `response.await` itself returns success (error is `nil`), so my naive check for an error and exiting early doesn't work.

Unfortunately the response type is `Response` which only has the method `ApiKey`, no way of inspecting it generically for errors, allowing us to exit early.

Without understanding `kafka-go` much better than I already do, I'm afraid that the only proposal I can offer is the following:

If I move the code that checks the request type from being before the request to afterwards, then it can build the correct list of topics to refresh the metadata for whilst excluding topics which it failed to recreate.

I have tested this approach locally and have found it works, so I will push a commit to this branch demonstrating this approach and you can consider whether you think it's a suitable solution :)

**Comment by omaskery** [comment]
I've also had a chance to add unit tests, it was a bit more involved than you and I had hoped, but I managed to find a solution that detected the issue in the original implementation and passes with the new implementation.

I don't know to what degree this test is a total hack, as I say I'm completely unfamiliar with this code-base, so I just kind of funbled through until I had a working test. Let me know what you think :)

**Review by achille-roussel — APPROVED** [review]
Thanks for the contribution @omaskery, the test looks good, I'll go ahead and merge 👍

**Pull request merged**
