### PR TITLE
Function for obtaining a list of topics #113

### PR DESCRIPTION
**Pull request by letum**

### CODE REVIEW

**Comment by letum** [comment]
If everything is ok, please create new release after accept.

**Comment by Pryz** [comment]
Seems to be a duplicate of https://github.com/segmentio/kafka-go/pull/259

**Comment by letum** [comment]
> Seems to be a duplicate of #259

Yes, it is another implementation. We can leave only your changes for `topicMetadataRequestV1.writeTo` and use `ReadPartitions()`, but at the moment the function returns empty list of Partitions if I call it without arguments.

**Comment by letum** [comment]
@Pryz please any feedback.

**Pull request closed without merging**
