### PR TITLE
recycle compression buffers

### PR DESCRIPTION
**Pull request by achille-roussel**
This PR should wrap up optimizing the write path of `*kafka.Conn` by recycling the buffers where compressed messages are written.

### CODE REVIEW

**Comment by achille-roussel** [comment]
We don’t have benchmarks that exercise compressed messages unfortunately (or I couldn’t find one). 
I’m working off of memory profiles I took from internal software. I can add a benchmark if you think it’s important.

**Comment by stevevls** [comment]
Sounds good!  No need to produce benchmarks...I was just curious.

**Comment by VictorDenisov** [comment]
Can this be merged. I would like to rework https://github.com/segmentio/kafka-go/pull/314 and continue work on transactions.

**Comment by achille-roussel** [comment]
@VictorDenisov yep 👍

**Pull request merged**
