### PR TITLE
Handle message sets with zero messages

### PR DESCRIPTION
**Pull request by Nilix007**
This is a hotfix for #653.

### CODE REVIEW

**Review by stevevls — COMMENTED** [review]
LGTM.  Would appreciate another look from @achille-roussel as a sanity check. 😄

**Comment by achille-roussel** [comment]
Thanks for the fix @Nilix007 

Would you happen to have a repro to share? Or maybe a unit test which highlights the fix?

**Comment by achille-roussel** [comment]
This appears to be related to https://github.com/segmentio/kafka-go/pull/709, @nlsun will take over.

**Comment by leedavis81** [comment]
@achille-roussel just to let you know, I tested PR this with the issue outlined in #709 and it didn't resolve the problem. The only way I can see that specific issue being resolved is by advancing the offset on the `Conn` object (which this PR doesn't attempt to do).

**Comment by iddqdeika** [comment]
we've got this issue as well.
as I understand this can be triggered by compacted topic.

when this hotfix to be merged?

**Comment by nlsun** [comment]
This issue has been fixed in https://github.com/segmentio/kafka-go/pull/813

**Pull request closed without merging**
