### PR TITLE
feature: limit batch queue size in partitionWriter.

### PR DESCRIPTION
**Pull request by sko00o**
kafka-go writer will create queues for batch messages, but there is no limit on length, batch queue will increase as fast as `queue.Put()` called.

Contributes-to: #819

Signed-off-by: Wenyu Li <lwylwy@outlook.com>

### CODE REVIEW

**Comment by achille-roussel** [comment]
Hello @sko00o 

I reviewed your benchmark code and I am a little concerned about modifying the API footprint of kafka-go to optimize for this use case:

I am curious whether the benchmark to put together is representative of the type of workloads that you will be seeing in production? It seems that you are writing all messages as fast as you can, one at a time from a single goroutine. In my experience, typical stream processors that rely on kafka tend to have more tamed load patterns, or use throttling mechanisms that limit the throughput of producers.

I want to make sure that new APIs we introduce are effective at supporting production use case, there is a long term maintenance cost we need to account for, which is why I am asking.

---
An alternative we discussed before with the team would be to have a `Flush` method on the `Writer` type, so clients have more control over when they choose to flush batches; do you think it would be useful in your case as well to limit memory utilization?

**Comment by sko00o** [comment]
Thanks for reply @achille-roussel 

> I am curious whether the benchmark to put together is representative of the type of workloads that you will be seeing in production? 

I'm working on some streaming log process projects that use Kafka as sink target. And I would call `writer.WriteMessages` in many goroutines.
I'm not sure that using throttling mechanisms before calling `WriteMessages` will solve my issue. There is no method to ensure that batch messages have been sent out.

> An alternative we discussed before with the team would be to have a `Flush` method on the `Writer` type, so clients have more control over when they choose to flush batches; do you think it would be useful in your case as well to limit memory utilization?

It would be useful to have `Flush` method, but the problem will be more complex. We already control the `BatchTimeout` , `BatchBytes` and `BatchSize`, maybe we don't have to care about when to call `Flush`. We have to set interval or max queue size for auto `Flush` call. I think blocking on `queue.Put` is easier.

**Comment by achille-roussel** [comment]
> I think blocking on queue.Put is easier.

Would it make sense to configure the writer in blocking mode then? (with Async=false)

Receiving writes from multiple goroutines and flushing when batches fill up is the common use case that the `kafka.Writer` type is usually used to solve for.

**Comment by sko00o** [comment]
> Would it make sense to configure the writer in blocking mode then? (with Async=false)

I create a benchmark for sync writer on multiple goroutines. https://github.com/sko00o/benchmark-kafka-go-clients/commit/54ea71dae737c51930f8075fcd2dde6ada006164 (I can limit the memory usage by limit the goroutines on write process. But it seems too slow.)

And I also create a benchmark for block batch queue based on my PR. https://github.com/sko00o/benchmark-kafka-go-clients/commit/b4f252baa337cd8238f1e6101e6d14c6924f34e0

**Comment by achille-roussel** [comment]
Do you have any details to share about your use cases?

I see you are making use of requiredAcks=none, which imply that maybe guaranteed deliveries are not a requirement here, maybe there's an option where we allow the `kafka.Writer` to drop messages to limit memory usage rather than blocking when configured in "fire and forget" mode?

**Comment by sko00o** [comment]
Sorry for late response.  `requiredAcks=none` is set for benchmark only here.  we need guarantee for delivery.

Use case here: 
* We need to pull jobs from message queue, the job describe the logging source and process actions.
* After process the logs line by line, we send the final logs to Kafka.

Maybe blocking in "fire and forget" mode is a poor design. I could run slowly on limited memory rather than drop messages before send. So the only solution here is set Async=false and limit the goroutines on writer process, right?

**Comment by achille-roussel** [comment]
Yes, if you need guarantees of message delivery you should use `Async: false` so you application receives feedback on success and failure of writes.

**Pull request closed without merging**
