### PR TITLE
support saslAuthenticate v0 in protocol package

### PR DESCRIPTION
**Pull request by rhansen2**
Potentially related to #868 and #795

### CODE REVIEW

**Review by achille-roussel — COMMENTED** [review]
Is there documentation you found that explains how v0 and v1 SASL messages differ?

**Comment by rhansen2** [comment]
The differences are documented here: https://kafka.apache.org/protocol#sasl_handshake (although I found the issue by comparing dialer network traffic to transport network traffic >.<)

**Comment by Jrmy2402** [comment]
When do you think you can merge this PR? I wait for it with impatience :)

**Review by achille-roussel — APPROVED** [review]

**Comment by rhansen2** [comment]
@Jrmy2402 This fix is now included in https://github.com/segmentio/kafka-go/releases/tag/v0.4.31

**Pull request merged**
